### ISSUE TITLE
Primary expression groupings do not serialize and then deserialize to the same rule

### ISSUE THREAD

**Issue by Northern-Lights** [VirusTotal/gyp#11]
I had this same issue with yara-parser, in which serialization to JSON and then deserialization back to YARA produces a different ruleset.

Consider this rule:

```
rule test {
  condition:
    true or (false and true)
}
```
It serializes to this:
```json
{
  "rules": [
    {
      "modifiers": {

      },
      "identifier": "test",
      "tags": [
      ],
      "meta": [
      ],
      "strings": [
      ],
      "condition": {
        "orExpression": {
          "terms": [
            {
              "boolValue": true
            },
            {
              "andExpression": {
                "terms": [
                  {
                    "boolValue": false
                  },
                  {
                    "boolValue": true
                  }
                ]
              }
            }
          ]
        }
      }
    }
  ]
}
```
It reserializes back to this:
```
rule test {
  condition:
    true or false and true
}
```
The groupings on the primary expressions seem to get lost. The easiest way to handle all of it seemed to be to throw parentheses around everything, but that makes formatting kind of ugly

**Comment by plusvic** [comment]
In 87b0750ac6574c1fe8b48db1a9ccf1b171f923d2 we have solved this issue, at least partially. Now the you can parse a rule and get an abstract syntax tree (AST) for that rule. If the AST is written back as source the grouping is maintained, even if it is unnecessary. However, if you save the AST as a protobuf or JSON, the grouping is lost, and you won't get it back. This happens only with parenthesis that are not really necessary, like in this case.
