### ISSUE TITLE
TextString escaped characters not properly handled

### ISSUE THREAD

**Issue by wayrick** [VirusTotal/gyp#23]
Something is wrong with escape sequences. When transforming a yara rule via gyp (i.e. test.yara -> y2j -> test.json -> j2y -> test_out.yara) a TextString containing escape sequences is changed and can become broken.

Most basic example:

```
$ cat test.yara
rule test {
strings:
    $s = "\""
condition:
    $s
}
$ ./y2j -o test.json test.yara 
$ ./j2y -o test_out.yara test.json
$ cat test_out.yara 

rule test {
  strings:
    $s = "\"
  condition:
    $s
}%
```

In the output yara rule the string is modified and broken (no ending quotation mark).

**Comment by wayrick** [comment]
I'm guessing it's related (though it's a new case). The escaped characters handling doesn't align well with Yara. Another case:

```
rule test {
strings:
    $s = "\r\n"
condition:
    $s
}
```

would get transformed to:
```
rule test {
strings:
    $s = "\x0d\x0a"
condition
    $s
}
```

This isn't accepted by yara... Not sure if it should be marked as a bug in gyp or an enhancement request in yara though (supporting things like "\r" seems sensible...)

¯\\\_(ツ)\_/¯

**Comment by plusvic** [comment]
The problem here is that strings are stored in unescaped form in the protobuf, and when they are reverted back we can't how they looked originally. So i think that the easiest solution is supporting \r in YARA, which makes sense after all.

**Comment by plusvic** [comment]
Done! https://github.com/VirusTotal/yara/commit/7a5b3a29cc381b75c42114c17779bee9ea10a79e
